get:
  summary: Display the configuration of this Open Build Service instance
  description: |
    Display the configuration of this Open Build Service instance.
  security:
    - basic_authentication: []
  responses:
    '200':
      description: >
        OK. The request has succeeded.
      content:
        application/xml; charset=utf-8:
          schema:
            $ref: '../components/schemas/configuration.yaml'
    '401':
      $ref: '../components/responses/unauthorized.yaml'
  tags:
    - Configuration
