openapi: 3.0.0

servers:
  - url: '/'

tags:
  - name: General Information
  - name: Groups

info:
  description: Open Build Service API
  version: '2.10.50'
  title: Open Build Service API
  contact:
    url: 'https://openbuildservice.org/'
    name: Open Build Service
  license:
    url: 'https://github.com/openSUSE/open-build-service/blob/master/COPYING'
    name: GNU General Public License v2.0

paths:
  /about:
    $ref: '/apidocs-new/paths/about.yaml'

  /architectures:
    $ref: '/apidocs-new/paths/architectures.yaml'

  /architectures/{architecture_name}:
    $ref: '/apidocs-new/paths/architectures_architecture_name.yaml'

  /group:
    $ref: '/apidocs-new/paths/group.yaml'

  /group/{group_title}:
    $ref: '/apidocs-new/paths/group_group_title.yaml'

components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic

externalDocs:
  url: 'https://openbuildservice.org/help/'
  description: Open Build Service - Documentation
