openapi: 3.0.0

servers:
  - url: '/'

tags:
  - name: General Information
  - name: Groups
  - name: Issue Trackers
  - name: Person

info:
  description: Open Build Service API
  version: '2.10.50'
  title: Open Build Service API
  contact:
    url: 'https://openbuildservice.org/'
    name: Open Build Service
  license:
    url: 'https://github.com/openSUSE/open-build-service/blob/master/COPYING'
    name: GNU General Public License v2.0

paths:
  /about:
    $ref: 'paths/about.yaml'

  /architectures:
    $ref: 'paths/architectures.yaml'
  /architectures/{architecture_name}:
    $ref: 'paths/architectures_architecture_name.yaml'

  /group:
    $ref: 'paths/group.yaml'
  /group/{group_title}:
    $ref: 'paths/group_group_title.yaml'

  /issue_trackers:
    $ref: 'paths/issue_trackers.yaml'
  /issue_trackers/{issue_tracker_name}:
    $ref: 'paths/issue_trackers_issue_tracker_name.yaml'

  /person:
    $ref: 'paths/person.yaml'

components:
  securitySchemes:
    basic_authentication:
      type: http
      scheme: basic

externalDocs:
  url: 'https://openbuildservice.org/help/'
  description: Open Build Service - Documentation
