name: Brakeman

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:3.1.1
    steps:
    - uses: actions/checkout@v2
    - name: Install Brakeman
      run: |
        gem install --no-format-executable brakeman -v 5.1.1
    - name: Brakeman
      run: |
        brakeman --rails6 -p src/api
