name: Add Comment with Diffend.io Links to PR
on:
  workflow_run:
    workflows: ['Create Diffend.io Links and Comment Text']
    types:
      - completed
permissions:
  contents: read
jobs:
  comment_diffend_io_links_to_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
      - name: Add Comment to PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment_text/comment_text.txt
          pr_number: ${{ github.event.workflow_run.pull_requests[0].number }}
